Repository simonsobs/SOLikeT, pull requests merged in 2022-11, with the labels that each got.

#80 Added Intrinsic Alignment redshift evolution modes
  notebooks/dev/cross_correlation_simulatedata.ipynb
  soliket/CrossCorrelationLikelihood.yaml
  soliket/cross_correlation.py
  soliket/tests/test_cross_correlation.py
Labels: enhancement, crosscorrelation

#83 Added exception and fallback for cosmopower not available
  soliket/cosmopower.py
  soliket/tests/test_cosmopower.py
Labels: bug, theory

#81 Add Hartlap and post-Hartlap corrections for GaussianData
  soliket/__init__.py
  soliket/gaussian.py
  soliket/gaussian_data.py
  soliket/tests/test_gaussian.py
Labels: enhancement

#89 BUG: pyCCL isn't optional due to cluster likelihood
  soliket/__init__.py
Labels: bug, clusters
