Repository simonsobs/SOLikeT, pull requests merged in 2023-03, with the labels that each got.

#110 General documentation
  docs/developers.rst
  docs/images/pr_docs_build.png
  docs/index.rst
Labels: documentation

#101 modify lensing test to compare with known chi_square computed with camb
  setup.cfg
  soliket/lensing/lensing.py
  soliket/tests/test_lensing.py
  soliket/tests/test_runs.py
Labels: tests, lensing

#117 Bias theory reworks
  docs/bias.rst
  docs/index.rst
  soliket/Bias.yaml
  soliket/Linear_bias.yaml
  soliket/bias.py
Labels: documentation, theory

#120 Fixes to local docs build config
  docs/conf.py
  tox.ini
Labels: bug, documentation

#118 remove txt paths for binning matrix and covmat
  soliket/lensing/lensing.py
Labels: lensing

#124 Address warnings in tox tests
  .github/workflows/testing.yml
  setup.cfg
  soliket-tests.yml
  soliket/clusters/clusters.py
  soliket/clusters/massfunc.py
  soliket/tests/data/des_s-act_kappa.toy-sim.sacc.fits
  soliket/tests/test_ccl.py
  soliket/tests/test_mflike.py
  tox.ini
Labels: repo
