Repository simonsobs/SOLikeT, pull requests merged in 2023-02, with the labels that each got.

#94 Add Hartlap correction to CrossCorrelation likelihoods
  soliket/CrossCorrelationLikelihood.yaml
  soliket/cross_correlation.py
  soliket/tests/test_cross_correlation.py
Labels: bug, crosscorrelation

#96 Move cosmopower to optional dep
  INSTALL.rst
  README.md
  requirements.txt
  setup.cfg
  tox.ini
Labels: repo, non cosmo

#98 Updated test loglikes to match for camb v1.4.0
  soliket/tests/test_clusters.py
  soliket/tests/test_cross_correlation.py
Labels: bug, tests

#103 Fix codecov not reporting
  tox.ini
Labels: bug, repo, non cosmo

#105 -v in pytest args
  tox.ini
Labels: repo

#106 Moved cosmopower default parameters to yaml files.
  soliket/CosmoPower.yaml
  soliket/CosmoPowerDerived.yaml
  soliket/cosmopower.py
Labels: documentation, theory

#100 37 implement sphinx for docs
  .readthedocs.yml
  INSTALL.rst
  README.md
  README.rst
  docs/conf.py
  docs/cosmopower.rst
  docs/index.rst
  docs/install.rst
  docs/requirements.txt
  setup.cfg
  tox.ini
Labels: documentation, repo, non cosmo
